$('#BotaoLogin').click(function(){
    window.open("../html/login.html");
})
$('#idBotaoCadastro').click(function(){
    window.open("../html/index.html");
})
$('#').click(function(){
    window.open("../html/");
})
$('#').click(function(){
    window.open("../html");
})